apiVersion: apps/v1
kind: Deployment
metadata:
  name: ureverse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ureverse
  template:
    metadata:
      labels:
        app: ureverse
    spec:
      containers:
      - name: ureverse
        image: dockerhub-username/ureverse-backend:latest
        ports:
        - containerPort: 8080
